# Workaround for https://github.com/conda-forge/opencv-feedstock/issues/493
MACOSX_SDK_VERSION:  # [osx]
  - 15.5             # [osx]

qt_version:
  - none
  - 6          # [not ppc64le]

# protobuf 6.31.1 was the last version that was used to build
# tensorflow as of March 28, 2026
# hmaarrfk only care about linux64 for this dual build
# so the selector here helps reduce the size of the build matrix
# 6.33.5 is the version from absl_grpc_proto_26Q1.yaml migration
libprotobuf:
- 6.31.1       # [linux64]
- 6.33.5

libopenvino_dev:
- 2025.4.1     # [linux64]
- 2026.0.0

zip_keys:                 # [linux64]
  -                       # [linux64]
    - libprotobuf         # [linux64]
    - libopenvino_dev     # [linux64]
